build:
        gcc addition.c log.c exponential.c modulus.c power.c subtraction.c code.c multiplication.c square_root.c square.c division.c factorial.c -lm ../Unity/unity.c -I../unity

Run:
        ./a.out
