
build:
    gcc addition.c log.c exponential.c modulus.c power.c  subtraction.c code.c multiplication.c square_root.c square.c division.c factorial.c test_calc.c -lm ../Unity/unity.c -Iunity

Run: 
    ./a.out