name: Cppcheck Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows

    steps:
    - uses: actions/checkout@v2
    - name: Install-Cppcheck
      run: sudo apt-get install cppcheck
    - name: Analyse
      run: cppcheck --enable==all 3_Implementation/src
